#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running

puppet resource file /tmp/8750522k ensure=absent force=true
puppet resource file /tmp/8750522k/research ensure=directory
puppet resource file /tmp/8750522k/research ensure=directory

cd /tmp/8750522k/research

git clone -b Prod https://github.com/earnestlim/8750522k_op_repo.git
cp -p /tmp/8750522k/research/8750522k_op_repo/8750522k_index.html /var/www/html




